name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  msrv:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.100.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --locked

  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check
      - run: cargo clippy --locked --all-targets -- -D warnings
      - run: cargo test --locked --all-targets
      - run: cargo build --release --locked

  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check advisories
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check bans licenses sources
